class Solution {
    public String intToRoman(int num) 
    {
        String s="";
        while(num>=1000)
        {
            s=s+"M";
            num-=1000;
        }
        while(num>=900)
        {
            s=s+"CM";
            num-=900;
        }
        while(num>=500)
        {
            s=s+"D";
            num-=500;
        }
        while(num>=400)
        {
            s=s+"CD";
            num-=400;
        }
        while(num>=100)
        {
            s=s+"C";
            num-=100;
        }
        while(num>=90)
        {
            s=s+"XC";
            num-=90;
        }
        while(num>=50)
        {
            s=s+"L";
            num-=50;
        }
        while(num>=40)
        {
            s=s+"XL";
            num-=40;
        }
        while(num>=10)
        {
            s=s+"X";
            num-=10;
        }
        while(num>=9)
        {
            s=s+"IX";
            num-=9;
        }
        while(num>=5)
        {
            s=s+"V";
            num-=5;
        }
        while(num>=4)
        {
            s=s+"IV";
            num-=4;
        }
        while(num>=1)
        {
            s=s+"I";
            num-=1;
        }
        return s;
    }
}